Give Jake some proper strict-age
JakeMakesStuff/MagicCap pull request #165
Opened 2019-05-31 21:54 UTC by vladfrangu

2019-05-31 21:56 UTC, IAmJSD requested changes
I can’t test this (on mobile) but I trust you. Please fix indentation though.

2019-05-31 22:00 UTC, IAmJSD submitted a review, later dismissed

2019-06-01 08:54 UTC, IAmJSD approved these changes

2019-06-01 08:57 UTC, IAmJSD requested changes
This fails by trying to lint node_modules.

2019-09-18 16:11 UTC, MattIPv4 requested changes
@vladfrangu Please, can you resolve the conflicts on this?

2026-07-18 13:07 UTC, closed without merging